name: CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    env:
      MIX_ENV: test
    strategy:
      matrix:
        include:
          - elixir: "1.13.x"
            otp: "24"
          - elixir: "1.14.x"
            otp: "25"
          - elixir: "1.16.x"
            otp: "26"
          - elixir: "1.17.3"
            otp: "27"
          - elixir: "1.18.4"
            otp: "27"
          - elixir: "1.19.0"
            otp: "28"
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - name: Install Dependencies
        run: mix deps.get
      - name: Check compile warnings
        run: mix compile --warnings-as-errors
      - name: Check format
        run: mix format --check-formatted
      - name: Unit tests
        run: mix test.unit
      - name: Property-based tests
        run: PROP_TEST_RUNTIME=30000 mix test.prop
